# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:
   inputs:
      logLevel:
        required: true
        description: ログレベル
        default: warning
      tags:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Generate ssh key
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # Runs a single command using the runners shell
      - name: SSH
        run: ssh -i key $SSH_USER@$SSH_HOST -p SSH_PORT
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      # Runs a set of commands using the runners shell
      - name: sudo su
        run: sudo su
      - name: cd
        run: cd $DEPLOY_PATH
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      - name: git pull
        run: git pull
